spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/filmfinderv2
    username: testjava
    password: testjava
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform:  org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8090